#cloud-config
users:
  - name: foobar
    # ssh_authorized_keys: # validated can ssh in with the key!
    groups: docker
    ssh_import_id:
      - gh:g0t4
    # mod vagrant user to add group root so can avoid sudo to read logs (well ok might need chmod too)
    gecos: gecos2
    
# maybes:
#   apt_update: true
#   apt_upgrade: false

#
#
#
#
# docs
#   https://github.com/canonical/cloud-init/tree/main/cloudinit/config/schemas
#   network:
#     schema:
#       https://github.com/canonical/cloud-init/blob/main/cloudinit/config/schemas/schema-network-config-v1.json
#       ref: https://cloudinit.readthedocs.io/en/latest/reference/base_config_reference.html
#   cloud-config:
#     https://raw.githubusercontent.com/canonical/cloud-init/main/cloudinit/config/schemas/schema-cloud-config-v1.json
#   versions of schemas: https://github.com/canonical/cloud-init/blob/main/cloudinit/config/schemas/versions.schema.cloud-config.json #  ( so far v1 )

# subiquity autoinstall schema
#   https://raw.githubusercontent.com/canonical/subiquity/main/autoinstall-system-setup-schema.json
#   https://raw.githubusercontent.com/canonical/subiquity/main/autoinstall-schema.json
#   https://ubuntu.com/server/docs/install/autoinstall-schema
