#cloud-config

final_message: |
  cloud-init has finished
  version: $version
  timestamp: $timestamp
  datasource: $datasource
  uptime: $uptime

# sudo cloud-init single --file /vagrant/parts/message.yaml --name final_message --frequency always
