#cloud-config



packages:
  - bat
  - jq
  - grc
  - command-not-found
  - silversearcher-ag




write_files:
- owner: vagrant:vagrant
  path: /home/vagrant/.hushlogin

# on every boot:
bootcmd:
- [ sh, -xc, "echo $(date) >> /tmp/bootcmd.log" ]


# on first boot:
runcmd:
- [ sh, -xc, "echo $(date) HELLO runcmd! >> /tmp/runcmd.log'" ]