#cloud-config

# yaml-language-server: $schema=https://raw.githubusercontent.com/canonical/cloud-init/main/cloudinit/config/schemas/schema-cloud-config-v1.json


packages:
  - bat
  - jq
  - grc
  - command-not-found
  - silversearcher-ag




write_files:
- owner: vagrant:vagrant
  path: /home/vagrant/.hushlogin

# on every boot:
bootcmd:
- [ sh, -xc, "echo $(date) >> /tmp/bootcmd.log" ]


# on first boot:
runcmd:
- [ sh, -xc, "echo $(date) HELLO runcmd! >> /tmp/runcmd.log'" ]